import Sparkle
import SwiftUI

// MARK: - View Model

/// Publishes when new updates can be checked by the user.
/// Used by CheckForUpdatesView to enable/disable the menu item.
@MainActor
final class CheckForUpdatesViewModel: ObservableObject {
    @Published var canCheckForUpdates = false

    init(updater: SPUUpdater) {
        updater.publisher(for: \.canCheckForUpdates)
            .receive(on: DispatchQueue.main)
            .assign(to: &$canCheckForUpdates)
    }
}

// MARK: - Menu View

/// SwiftUI view for the "Check for Updates…" menu item.
/// This intermediate view is necessary for the disabled state on the menu item
/// to work properly before macOS Monterey.
/// See: https://stackoverflow.com/questions/68553092/menu-not-updating-swiftui-bug
struct CheckForUpdatesView: View {
    @ObservedObject private var viewModel: CheckForUpdatesViewModel
    private let updater: SPUUpdater

    init(updater: SPUUpdater) {
        self.updater = updater
        self.viewModel = CheckForUpdatesViewModel(updater: updater)
    }

    var body: some View {
        Button("检查更新…") {
            updater.checkForUpdates()
        }
        .disabled(!viewModel.canCheckForUpdates)
    }
}

// MARK: - Updater Controller Wrapper

/// Manages the Sparkle updater lifecycle for the application.
///
/// Sparkle reads its configuration from the app bundle's Info.plist:
/// - SUFeedURL: appcast feed URL
/// - SUPublicEDKey: EdDSA public key for update signature verification
///
/// Use `scripts/build-app.sh` to create a proper .app bundle with Info.plist.
///
/// Usage:
/// ```swift
/// @main
/// struct MyApp: App {
///     private let updaterManager = UpdaterManager()
///
///     var body: some Scene { ... }
///         .commands {
///             updaterManager.commands
///         }
/// }
/// ```
@MainActor
final class UpdaterManager {
    let updaterController: SPUStandardUpdaterController

    init() {
        // Start the updater automatically on launch.
        // Sparkle checks for updates in the background once every 24 hours by default.
        // The first check is deferred to the second launch to avoid bothering the user
        // on first impression.
        updaterController = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
    }

    /// The SPUUpdater instance for direct API access.
    var updater: SPUUpdater {
        updaterController.updater
    }

    /// SwiftUI commands to insert into the application menu.
    var commands: some Commands {
        CommandGroup(after: .appInfo) {
            CheckForUpdatesView(updater: updater)
        }
    }
}

// MARK: - Configuration Reference

/// Sparkle configuration constants for documentation purposes.
///
/// These values must be set in the app bundle's Info.plist:
/// - SUFeedURL = feedURLString
/// - SUPublicEDKey = (generated by Sparkle's generate_keys tool)
///
/// The Info.plist is located at native/Info.plist and is copied into
/// the .app bundle by scripts/build-app.sh.
enum UpdaterConfig {
    /// Appcast feed URL (for reference — configure in Info.plist SUFeedURL).
    static let feedURLString = "https://sunnyhot.github.io/car-rental-optimizer/appcast.xml"
}
